version: '3.8'
services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_DEPENDENCIES=netcat
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    init: true
    stdin_open: true
    tty: true
